name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies (if needed)
      run: npm install

    - name: Create directories for config.js
      run: mkdir -p src/pages/classicConcert

    - name: Insert API keys
      run: |
        echo "const API_KEY_MAP = '${{ secrets.API_KEY_MAP }}';" > src/pages/classicConcert/config.js
        echo "const API_KEY_WEATHER = '${{ secrets.API_KEY_WEATHER }}';" >> src/pages/classicConcert/config.js
        echo "const API_KEY_SEARCH = '${{ secrets.API_KEY_SEARCH }}';" >> src/pages/classicConcert/config.js

    - name: Build project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
